
import ForgetPassword from '@/app/[lang]/components/authComponents/ForgetPassword';
import React from 'react';
import { metaDataText } from '../../data/data';

// export const metadata = {
//     title: " فراموشی رمز عبور ",
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
    return {
      title: {
        default: metaDataText.forgotPassword.title[params.lang],
      },
      description: `${ metaDataText.forgotPassword.description[params.lang].substring(0, 156)} ...`,
      keywords: [ ...metaDataText.forgotPassword.keywords[params.lang]],
      metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
      alternates: {
        canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/forgot-password`,
        languages: {
          fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/forgot-password`,
          en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/forgot-password`,
          ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/forgot-password`,
        },
      },
      owner: metaDataText.forgotPassword.owner[params.lang],
      creator: metaDataText.forgotPassword.creator[params.lang],
      openGraph: {
        title: metaDataText.forgotPassword.title[params.lang],
        description: `${ metaDataText.forgotPassword.description[params.lang].substring(0, 156)} ...`,
      },
    };
  }
//? =======================  / END generateMetadata =======================

const forgotPassword = () => {
    return (
        <div>
            <ForgetPassword/>
        </div>
    );
};

export default forgotPassword;