
import React from 'react';
import Products from '@/app/[lang]/components/productsComponents/Products';
import { metaDataText } from '../../data/data';

// export const metadata = {
//   title:' پانوتک | فروشگاه ',
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
  return {
    title: {
      default: metaDataText.Store.title[params.lang],
    },
    description: `${ metaDataText.Store.description[params.lang].substring(0, 156)} ...`,
    keywords: [ ...metaDataText.Store.keywords[params.lang]],
    metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
    alternates: {
      canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/products`,
      languages: {
        fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/products`,
        en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/products`,
        ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/products`,
      },
    },
    owner: metaDataText.Store.owner[params.lang],
    creator: metaDataText.Store.creator[params.lang],
    openGraph: {
      title: metaDataText.Store.title[params.lang],
      description: metaDataText.Store.description[params.lang],
    },
  };
}
//? =======================  / END generateMetadata =======================

const products = ({ params, searchParams }) => {
    
  return (
    <div>
      <Products
        category={searchParams.category || "null"}
        page={searchParams.page || 1}
        lang={params.lang}
        keyword={searchParams.keyword || "null"}
      />
    </div>
);
};

export default products;