import React from "react";
import Product from "@/app/[lang]/components/productsComponents/Product";
import { metaDataText } from "@/app/[lang]/data/data";
import { GetProductBySlugFunction } from "@/app/[lang]/functions";
import { notFound } from "next/navigation";

// export const metadata = {
//     title:' پانوتک | فروشگاه | محصول ',
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
  const lang = params.lang;
  const product = await GetProductBySlugFunction(lang, params.productSlug);
  if (!product) notFound();

  return {
    title: {
      default: `
      ${product.name[lang]} |
      ${metaDataText.Store.title[lang]} 
      `,
    },
    description: `${product.fullDescription[lang].substring(0, 156)} ...`,
    keywords: [...product.keywords[lang]],
    metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
    alternates: {
      canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/products/${product.slug.fa}`,
      languages: {
        fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/products/${product.slug.fa}`,
        en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/products/${product.slug.fa}`,
        ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/products/${product.slug.fa}`,
      },
    },
    openGraph: {
      images: [`/${product.images[0].name}`],
      title: product.name[lang],
      description: `${product.fullDescription[lang].substring(0, 156)} ...`,
    },
  };
}
//? =======================  / END generateMetadata =======================

const product = ({ params, searchParams }) => {
  return (
    <div>
      <Product params={params} />
    </div>
  );
};

export default product;
