
import ContactUs from "@/app/[lang]/components/contactUsAboutComponents/ContactUs/ContactUs";
import React from 'react';
import { metaDataText } from "../../data/data";

// export const metadata = {
//     title:' پانوتک | تماس با ما ',
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
    return {
      title: {
        default: metaDataText.Contact.title[params.lang],
      },
      description: `${ metaDataText.Contact.description[params.lang].substring(0, 156)} ...`,
      keywords: [ ...metaDataText.Contact.keywords[params.lang]],
      metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
      alternates: {
        canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/contact-us`,
        languages: {
          fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/contact-us`,
          en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/contact-us`,
          ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/contact-us`,
        },
      },
      owner: metaDataText.Contact.owner[params.lang],
      creator: metaDataText.Contact.creator[params.lang],
      openGraph: {
        title: metaDataText.Contact.title[params.lang],
        description: metaDataText.Contact.description[params.lang],
      },
    };
  }
//? =======================  / END generateMetadata =======================

const contactUs = () => {
    return (
        <div>
            <ContactUs/>
        </div>
    );
};

export default contactUs;