import { vazirFD } from "./[lang]/fonts/font";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";

import AuthProvider from "./[lang]/providers/AuthProvider";
import ToastProvider from "./[lang]/providers/ToastProvider";
import ReduxProviders from "./[lang]/providers/ReduxProviders";
import { cookies } from "next/headers";


// export const metadata = {
//   title: "محمد هادی ثامنی",
//   description: "Generated by create next app",
// };

const libre = Libre_Franklin({ subsets: ["latin"] });

export default function RootLayout({ children, params }) {
  const lang = cookies().get("NEXT_LOCALE")?.value || "fa";
  return (
    // <html lang="fa" dir="rtl">
    <html lang={lang} dir={lang === "en" ? "ltr" : "rtl"}>
      <body
        className={`${lang === "en" ? libre.className : vazirFD.className} selection:text-green-600 selection:bg-indigo-300`}
      >
        <AuthProvider>
          <ReduxProviders>
            <ToastProvider>
              {children}
            </ToastProvider>
          </ReduxProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
