
import Register from '@/app/[lang]/components/authComponents/Register';
import React from 'react';
import { metaDataText } from '../../data/data';

// export const metadata = {
//     title: " عضویت ",
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
    return {
      title: {
        default: metaDataText.register.title[params.lang],
      },
      description: `${ metaDataText.register.description[params.lang].substring(0, 156)} ...`,
      keywords: [ ...metaDataText.register.keywords[params.lang]],
      metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
      alternates: {
        canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/register`,
        languages: {
          fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/register`,
          en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/register`,
          ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/register`,
        },
      },
      owner: metaDataText.register.owner[params.lang],
      creator: metaDataText.register.creator[params.lang],
      openGraph: {
        title: metaDataText.register.title[params.lang],
        description: `${ metaDataText.register.description[params.lang].substring(0, 156)} ...`,
      },
    };
  }
//? =======================  / END generateMetadata =======================

const register = ({params}) => {
    return (
        <div>
            <Register params={params}/>
        </div>
    );
};

export default register;