
import React from 'react';
import ShowBlogs from '@/app/[lang]/components/blogsComponents/ShowBlogs';
import { metaDataText } from '../../data/data';

// export const metadata = {
//     title:' پانوتک | وبلاگ ',
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
    return {
      title: {
        default: metaDataText.Blog.title[params.lang],
      },
      description: `${ metaDataText.Blog.description[params.lang].substring(0, 156)} ...`,
      keywords: [ ...metaDataText.Blog.keywords[params.lang]],
      metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
      alternates: {
        canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/blogs`,
        languages: {
          fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/blogs`,
          en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/blogs`,
          ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/blogs`,
        },
      },
      owner: metaDataText.Blog.owner[params.lang],
      creator: metaDataText.Blog.creator[params.lang],
      openGraph: {
        title: metaDataText.Blog.title[params.lang],
        description: metaDataText.Blog.description[params.lang],
      },
    };
  }
//? =======================  / END generateMetadata =======================

const blogs = ({ params, searchParams }) => {

    return (
        <div>
            <ShowBlogs params={params} searchParams={searchParams}/>
        </div>
    );
};

export default blogs;