
import BackgroundProfile from "../components/adminComponents/HeaderSidbar/BackgroundProfile";
import SidbarProfile from "../components/adminComponents/HeaderSidbar/SidbarProfile";
import "../../globals.css";

export const metadata = {
  title: "پنل ادمین | شرکت پانوتک",
  description: "Generated by create next app",
};

export default function AdminLayout({ children,params }) {
  return (
      <>
          <BackgroundProfile/>
          <SidbarProfile lang={params.lang}/>
          <div className='ps-10 lg:ps-60 pt-24'>
            {children}
          </div>
      </>
   
  );
}
