
import Gallery from '@/app/[lang]/components/gallery/Gallery';
import React from 'react';
import { metaDataText } from '../../data/data';

// export const metadata = {
//     title:' پانوتک | گالری ',
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
    return {
      title: {
        default: metaDataText.Gallery.title[params.lang],
      },
      description: `${ metaDataText.Home.description[params.lang].substring(0, 156)} ...`,
      keywords: [ ...metaDataText.Home.keywords[params.lang]],
      metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
      alternates: {
        canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/gallery`,
        languages: {
          fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/gallery`,
          en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/gallery`,
          ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/gallery`,
        },
      },
      owner: metaDataText.Home.owner[params.lang],
      creator: metaDataText.Home.creator[params.lang],
      openGraph: {
        title: metaDataText.Home.title[params.lang],
        description: metaDataText.Home.description[params.lang],
      },
    };
  }
//? =======================  / END generateMetadata =======================

const gallery = ({ params, searchParams }) => {
    return (
        <div>
            <Gallery lang={params.lang}/>
        </div>
    );
};

export default gallery;