import SingleNews from "@/app/[lang]/components/blogsComponents/SingleNews";
import { metaDataText } from "@/app/[lang]/data/data";
import { GetNewsBySlugFunction } from "@/app/[lang]/functions";
import { notFound } from "next/navigation";
import React from "react";

// export const metadata = {
//     title:' پانوتک | وبلاگ | خبر ',
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
  const lang = params.lang;
  const news = await GetNewsBySlugFunction(lang, params.newsSlug);
  if (!news) notFound();

  return {
    title: {
      default: `
      ${news.title[params.lang]}  |
      ${metaDataText.Blog.newsTitle[params.lang]} |
      ${metaDataText.Blog.title[params.lang]} 
      `,
    },
    description: `${news.firstBody[params.lang].substring(0, 156)} ...`,
    keywords: [...news.keywords[params.lang]],
    metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
    alternates: {
      canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/blogs/news/${news.slug.fa}`,
      languages: {
        fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/blogs/news/${news.slug.fa}`,
        en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/blogs/news/${news.slug.en}`,
        ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/blogs/news/${news.slug.ar}`,
      },
    },
    openGraph: {
      images: [`/${news.images[0].name}`],
      title: news.title[params.lang],
      description: `${news.firstBody[params.lang].substring(0, 156)} ...`,
    },
  };
}
//? =======================  / END generateMetadata =======================

const blog = ({ params, searchParams }) => {
  return (
    <div>
      <SingleNews params={params} />
    </div>
  );
};

export default blog;
