import React from "react";
import Home from "../components/homeComponents/Home";
import { metaDataText } from "../data/data";

// export const metadata = {
//   title:' پانوتک ',
//   description: "Generated by create next app",
// };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
  return {
    title: {
      default: metaDataText.Home.title[params.lang],
    },
    description: `${metaDataText.Home.description[params.lang].substring(
      0,
      156
    )} ...`,
    keywords: [...metaDataText.Home.keywords[params.lang]],
    metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
    alternates: {
      canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa`,
      languages: {
        fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa`,
        en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en`,
        ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar`,
      },
    },
    other: {
      owner: metaDataText.Home.owner[params.lang],
      frontEndDeveloper: metaDataText.Home.feDeveloper,
      backEndDeveloper: metaDataText.Home.beDeveloper,
    },
    creator: metaDataText.Home.creator,
    openGraph: {
      title: metaDataText.Home.title[params.lang],
      description: metaDataText.Home.description[params.lang],
    },
  };
}
//? =======================  / END generateMetadata =======================

const home = ({ params, searchParams }) => {
  const lang = params.lang;

  return (
    <div>
      <Home lang={lang} />
    </div>
  );
};

export default home;
