import Cart from "@/app/[lang]/components/cartComponents/Cart";
import React from "react";
import { metaDataText } from "../../data/data";

// export const metadata = {
//     title:' پانوتک | سبدخرید ',
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
  return {
    title: {
      default: metaDataText.Cart.title[params.lang],
    },
    description: `${metaDataText.Cart.description[params.lang].substring(
      0,
      156
    )} ...`,
    keywords: [...metaDataText.Cart.keywords[params.lang]],
    metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
    alternates: {
      canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/cart`,
      languages: {
        fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/cart`,
        en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/cart`,
        ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/cart`,
      },
    },
    owner: metaDataText.Cart.owner[params.lang],
    creator: metaDataText.Cart.creator[params.lang],
    openGraph: {
      title: metaDataText.Cart.title[params.lang],
      description: metaDataText.Cart.description[params.lang],
    },
  };
}
//? =======================  / END generateMetadata =======================

const cart = ({ params }) => {
  return (
    <div>
      <Cart params={params} />
    </div>
  );
};

export default cart;
