import React from "react";
import { metaDataText } from "../../../data/data";
import ResetPassword from "../../../components/authComponents/ResetPassword";

// export const metadata = {
//     title: " فراموشی رمز عبور ",
//     description: "Generated by create next app",
//   };

//? ======================= START generateMetadata =======================
export async function generateMetadata({ params, searchParams }, parent) {
  return {
    title: {
      default: metaDataText.changePassword.title[params.lang],
    },
    description: `${metaDataText.changePassword.description[
      params.lang
    ].substring(0, 156)} ...`,
    keywords: [...metaDataText.changePassword.keywords[params.lang]],
    metadataBase: new URL(process.env.NEXT_PUBLIC_PANOTECH_BASE_URL),
    alternates: {
      canonical: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/change-password`,
      languages: {
        fa: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/fa/change-password`,
        en: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/en/change-password`,
        ar: `${process.env.NEXT_PUBLIC_PANOTECH_BASE_URL}/ar/change-password`,
      },
    },
    owner: metaDataText.changePassword.owner[params.lang],
    creator: metaDataText.changePassword.creator[params.lang],
    openGraph: {
      title: metaDataText.changePassword.title[params.lang],
      description: `${metaDataText.changePassword.description[
        params.lang
      ].substring(0, 156)} ...`,
    },
  };
}
//? =======================  / END generateMetadata =======================

const ResetPasswordPage = () => {
  return (
    <div>
      {/* <ResetPassword/> */}
      <ResetPassword />
    </div>
  );
};

export default ResetPasswordPage;
