
import { vazirFD } from "../fonts/font";

export const metadata = {
  title: " سوالات متدامل ",
  description: "Generated by create next app",
};

export default function FaqLayout({ children }) {
  return (
      <div className={vazirFD.className}>
        {children}
      </div>
  );
}
